name: Validate

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install LLVM 21
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21"

      - name: Install dependencies
        run: cargo install cargo-llvm-cov

      - name: Run cargo llvm-cov
        run: cargo llvm-cov

      - name: Run cargo test
        run: cargo test

      - name: Run example expect list
        run: python3 ./scripts/example_expect.py list
